# database ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    url: jdbc:mariadb://localhost:3305/cocotexi
    #    mysql? ??? ??? ?? ??? ?? ???.
    username: root
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update