version: "3.2"
services:
  frontend:
    restart: always
    command: npm start
    container_name: frontend
    build:
      context: ./Front-end
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    stdin_open: true
