# node verion : 18.18.2
FROM node:18.18.2-alpine as builder
# 작업 위치 지정
# WORKDIR /S09P31S101/Front-end
WORKDIR /app


# 현재 파일을 이미지의 /app 위치에 복사
COPY package*.json ./
COPY . ./

# package.json에 명시된 의존성 설치
RUN npm install	
RUN npm install -g webpack-cli

# 빌드 시작
RUN npm run build

# nginx 
FROM nginx:latest
RUN mkdir /app
WORKDIR /app/Front-end

# 기존 환경 설정 제거
RUN rm /etc/nginx/conf.d/default.conf
# 디렉토리의 conf 파일을 복사
COPY ./nginx.conf /etc/nginx/conf.d
# builder로 부터 /app/build를 복사해옵니다.
COPY --from=builder /app/build /app/build
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]